### ISSUE TITLE
Tag 1.1 release?

### ISSUE THREAD

**Issue by tuupola** [neomerx/cors-psr7#30]
Would it be possible to tag an 1.1 release?

This is because versions before 1.0.4 throw an error with PHP 7.2 because of `assert('is_string($url) || is_array($url)');` in `ParsedUrl.php`. Currently only way of ignoring everything below `1.0.4` would be to manually list all the minor releases.

```
"neomerx/cors-psr7": "1.0.4|1.0.5|1.0.6|1.0.7|1.0.8|1.0.9|1.0.11|1.0.12|1.0.13",
```

This not optimal and requires manually updating `composer.json` on my side always when `neomerx/cors-psr7` has a new release.

**Comment by neomerx** [comment]
Hi,

Sorry, but I don't get it. The line you're referring to was removed more than [2 years ago on Mar 18, 2016
](https://github.com/neomerx/cors-psr7/commit/beefc866fe3735bd1238ae26b6fcfb6ea42a99f9#diff-e3659be8dce60138e33abdab9c0b2625).

As far as I understand you're using PHP 7.2 (as I do btw) and keep using very old version which was not tested on PHP 7.2 due to it didn't existed at that time (7.2 was released on Nov 30 2017).

Why just not upgrade to the latest version which was actually tested on 7.2? Have you got any issues with that?

**Comment by neomerx** [comment]
Can you please try the latest version? I expect it should work just fine.

**Comment by tuupola** [comment]
Yes, latest version works ok, that was not the issue. In any case I can do some workaround this.

**Comment by neomerx** [comment]
As far as I understand lowest from 1.0.4|1.0.5|1.0.6|1.0.7|1.0.8|1.0.9|1.0.11|1.0.12|1.0.13 would be 1.0.4 so the whole line can be replaced with 1.0.4 (or any other version you need).

Anyways, if I can help you please don't hesitate to ask.

**Comment by tuupola** [comment]
Read the composer docs again. You are correct `^1.0.4` allows `>=1.0.4 <2.0.0`. Thanks!
